# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1140, 640)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Form.sizePolicy().hasHeightForWidth())
        Form.setSizePolicy(sizePolicy)
        Form.setMinimumSize(QtCore.QSize(1140, 640))
        Form.setMaximumSize(QtCore.QSize(1140, 640))
        self.leftbg = QtWidgets.QLabel(Form)
        self.leftbg.setGeometry(QtCore.QRect(0, 0, 270, 640))
        self.leftbg.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.leftbg.setText("")
        self.leftbg.setObjectName("leftbg")
        self.gridLayoutWidget = QtWidgets.QWidget(Form)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(40, 170, 231, 241))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.menu1 = QtWidgets.QLabel(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.menu1.sizePolicy().hasHeightForWidth())
        self.menu1.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.menu1.setFont(font)
        self.menu1.setObjectName("menu1")
        self.gridLayout.addWidget(self.menu1, 0, 1, 1, 1)
        self.icon3 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.icon3.setMinimumSize(QtCore.QSize(40, 40))
        self.icon3.setMaximumSize(QtCore.QSize(40, 40))
        self.icon3.setStyleSheet("image: url(:/res/order.png);")
        self.icon3.setText("")
        self.icon3.setObjectName("icon3")
        self.gridLayout.addWidget(self.icon3, 2, 0, 1, 1)
        self.menu4 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.menu4.setFont(font)
        self.menu4.setObjectName("menu4")
        self.gridLayout.addWidget(self.menu4, 3, 1, 1, 1)
        self.menu2 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.menu2.setFont(font)
        self.menu2.setObjectName("menu2")
        self.gridLayout.addWidget(self.menu2, 1, 1, 1, 1)
        self.icon4 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.icon4.setMinimumSize(QtCore.QSize(40, 40))
        self.icon4.setMaximumSize(QtCore.QSize(40, 40))
        self.icon4.setStyleSheet("image: url(:/res/calendar_fill.png);")
        self.icon4.setText("")
        self.icon4.setObjectName("icon4")
        self.gridLayout.addWidget(self.icon4, 3, 0, 1, 1)
        self.icon5 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.icon5.setMinimumSize(QtCore.QSize(40, 40))
        self.icon5.setMaximumSize(QtCore.QSize(40, 40))
        self.icon5.setStyleSheet("image: url(:/res/favorites_fill.png);")
        self.icon5.setText("")
        self.icon5.setObjectName("icon5")
        self.gridLayout.addWidget(self.icon5, 4, 0, 1, 1)
        self.icon1 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.icon1.setMinimumSize(QtCore.QSize(40, 40))
        self.icon1.setMaximumSize(QtCore.QSize(40, 40))
        self.icon1.setSizeIncrement(QtCore.QSize(0, 0))
        self.icon1.setBaseSize(QtCore.QSize(0, 0))
        self.icon1.setStyleSheet("image: url(:/res/collection.png);")
        self.icon1.setText("")
        self.icon1.setObjectName("icon1")
        self.gridLayout.addWidget(self.icon1, 0, 0, 1, 1)
        self.icon2 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.icon2.setMinimumSize(QtCore.QSize(40, 40))
        self.icon2.setMaximumSize(QtCore.QSize(40, 40))
        self.icon2.setStyleSheet("image: url(:/res/confirm.png);")
        self.icon2.setText("")
        self.icon2.setObjectName("icon2")
        self.gridLayout.addWidget(self.icon2, 1, 0, 1, 1)
        self.menu3 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.menu3.setFont(font)
        self.menu3.setObjectName("menu3")
        self.gridLayout.addWidget(self.menu3, 2, 1, 1, 1)
        self.menu5 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.menu5.setFont(font)
        self.menu5.setObjectName("menu5")
        self.gridLayout.addWidget(self.menu5, 4, 1, 1, 1)
        self.label_11 = QtWidgets.QLabel(Form)
        self.label_11.setGeometry(QtCore.QRect(0, 0, 270, 160))
        self.label_11.setStyleSheet("border-image: url(:/res/header.png);\n"
"")
        self.label_11.setText("")
        self.label_11.setObjectName("label_11")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(20, 100, 230, 24))
        self.label.setMaximumSize(QtCore.QSize(230, 24))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(20, 130, 230, 15))
        self.label_2.setMaximumSize(QtCore.QSize(230, 15))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setBold(False)
        font.setWeight(50)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(20, 20, 60, 60))
        self.label_3.setStyleSheet("image: url(:/res/headimg1.png);\n"
"")
        self.label_3.setText("")
        self.label_3.setObjectName("label_3")
        self.rightbg = QtWidgets.QLabel(Form)
        self.rightbg.setGeometry(QtCore.QRect(270, 0, 870, 640))
        self.rightbg.setStyleSheet("background-color: rgb(253, 177, 177);\n"
"")
        self.rightbg.setText("")
        self.rightbg.setObjectName("rightbg")
        self.addbtn = QtWidgets.QLabel(Form)
        self.addbtn.setGeometry(QtCore.QRect(1050, 550, 80, 80))
        self.addbtn.setStyleSheet("image: url(:/res/add_fill.png);")
        self.addbtn.setText("")
        self.addbtn.setObjectName("addbtn")
        self.gridLayoutWidget_2 = QtWidgets.QWidget(Form)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(300, 0, 811, 91))
        self.gridLayoutWidget_2.setObjectName("gridLayoutWidget_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.gridLayoutWidget_2)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_6 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_6.setMinimumSize(QtCore.QSize(30, 30))
        self.label_6.setStyleSheet("image: url(:/res/delete1.png);")
        self.label_6.setText("")
        self.label_6.setObjectName("label_6")
        self.gridLayout_2.addWidget(self.label_6, 0, 4, 1, 1)
        self.checkBox = QtWidgets.QCheckBox(self.gridLayoutWidget_2)
        self.checkBox.setText("")
        self.checkBox.setObjectName("checkBox")
        self.gridLayout_2.addWidget(self.checkBox, 0, 6, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_5.setMinimumSize(QtCore.QSize(30, 30))
        self.label_5.setStyleSheet("image: url(:/res/back.png);")
        self.label_5.setText("")
        self.label_5.setObjectName("label_5")
        self.gridLayout_2.addWidget(self.label_5, 0, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(3)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        self.label_4.setText("")
        self.label_4.setObjectName("label_4")
        self.gridLayout_2.addWidget(self.label_4, 0, 1, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_8.setMinimumSize(QtCore.QSize(30, 30))
        self.label_8.setStyleSheet("image: url(:/res/back_1.png);")
        self.label_8.setText("")
        self.label_8.setObjectName("label_8")
        self.gridLayout_2.addWidget(self.label_8, 0, 2, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_7.setMinimumSize(QtCore.QSize(10, 0))
        self.label_7.setText("")
        self.label_7.setObjectName("label_7")
        self.gridLayout_2.addWidget(self.label_7, 0, 5, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_9.setMinimumSize(QtCore.QSize(10, 0))
        self.label_9.setText("")
        self.label_9.setObjectName("label_9")
        self.gridLayout_2.addWidget(self.label_9, 0, 3, 1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "ToDo"))
        self.menu1.setText(_translate("Form", "全部"))
        self.menu4.setText(_translate("Form", "日程"))
        self.menu2.setText(_translate("Form", "待办事项"))
        self.menu3.setText(_translate("Form", "备忘录"))
        self.menu5.setText(_translate("Form", "个人空间"))
        self.label.setText(_translate("Form", "登录账号"))
        self.label_2.setText(_translate("Form", "登录后可同步数据"))

